package seletorcores;

import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.MouseEvent;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael
 */
public class ColorPanel extends javax.swing.JPanel {

    private static String COLOR_FORMAT = "RGB(%03d, %03d, %03d, %03d) ";
    private Set<ColorChangedListener> components = new HashSet<ColorChangedListener>();
    Random random = new Random();

    /** Creates new form ColorPanel */
    public ColorPanel() {
        initComponents();
        // Init Colors
        this.setBackground(this.createRandomColor());
    }

    private Color createRandomColor() {
        return new Color(random.nextInt(256), random.nextInt(256), random.nextInt(256), 255);
    }

    private void showColor() {
        Color bkColor = this.getBackground();
        this.pnlCor.setBackground(new Color(255, 255, 255, bkColor.getAlpha()));
        this.lblCor.setText(String.format(COLOR_FORMAT, bkColor.getRed(), bkColor.getGreen(), bkColor.getBlue(), bkColor.getAlpha()));
    }

    public void setCor(Color color, ColorChangedListener source) {
        this.setBackground(color);
        showColor();
        for (ColorChangedListener colorChangedListener : components) {
            if (colorChangedListener != source) {
                colorChangedListener.colorChanged(color);
            }
        }
    }

    public boolean addColorChangedListener(ColorChangedListener component) {
        return this.components.add(component);
    }

    public void init() {
        this.setCor(this.getBackground(), null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCor = new javax.swing.JPanel();
        lblCor = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lblCor.setBackground(new Color(0, 0, 0, 255));
        lblCor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCor.setText("RGB(000,000,000)");

        javax.swing.GroupLayout pnlCorLayout = new javax.swing.GroupLayout(pnlCor);
        pnlCor.setLayout(pnlCorLayout);
        pnlCorLayout.setHorizontalGroup(
            pnlCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCor))
        );
        pnlCorLayout.setVerticalGroup(
            pnlCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCor)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(pnlCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(pnlCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON3) {
            this.setCor(this.createRandomColor(), null);
        } else if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            JOptionPane.showMessageDialog(this, new ColorDescriptionPanel(this.getBackground()), "Valor da cor", JOptionPane.PLAIN_MESSAGE);
        }
        KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
    }//GEN-LAST:event_formMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCor;
    private javax.swing.JPanel pnlCor;
    // End of variables declaration//GEN-END:variables
}
