/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SeletorCores3.java
 *
 * Created on 03/06/2009, 22:47:54
 */
package seletorcores;

import java.awt.KeyboardFocusManager;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author rafael
 */
public class SeletorCores3 extends JPanel {

    /** Creates new form SeletorCores3 */
    public SeletorCores3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multiSliderComponentR_G_B_A = new seletorcores.multisliders.MultiSliderComponentR_G_B_A();
        colorPanel = new seletorcores.ColorPanel();
        multiSliderComponentRGBA = new seletorcores.multisliders.MultiSliderComponentRGBA();
        multiSliderComponentRGB_A = new seletorcores.multisliders.MultiSliderComponentRGB_A();
        multiSliderComponentRG_B_A = new seletorcores.multisliders.MultiSliderComponentRG_B_A();
        multiSliderComponentR_GB_A = new seletorcores.multisliders.MultiSliderComponentR_GB_A();
        multiSliderComponentRB_G_A = new seletorcores.multisliders.MultiSliderComponentRB_G_A();
        multiSliderComponentR_GBA = new seletorcores.multisliders.MultiSliderComponentR_GBA();
        multiSliderComponentRGA_B = new seletorcores.multisliders.MultiSliderComponentRGA_B();
        multiSliderComponentRBA_G = new seletorcores.multisliders.MultiSliderComponentRBA_G();
        multiSliderComponentRG_BA = new seletorcores.multisliders.MultiSliderComponentRG_BA();
        multiSliderComponentRB_GA = new seletorcores.multisliders.MultiSliderComponentRB_GA();
        multiSliderComponentRA_GB = new seletorcores.multisliders.MultiSliderComponentRA_GB();
/*
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seletor de Cores");
        setLocationByPlatform(true);
        setName("frmCor"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
*/
        multiSliderComponentR_G_B_A.setColorPanel(colorPanel);

        this.colorPanel.addColorChangedListener(this.multiSliderComponentR_G_B_A);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRGBA);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRGB_A);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRA_GB);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRBA_G);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRB_GA);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRB_G_A);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRGA_B);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRG_BA);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentRG_B_A);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentR_GBA);
        this.colorPanel.addColorChangedListener(this.multiSliderComponentR_GB_A);

        multiSliderComponentRGBA.setColorPanel(colorPanel);

        multiSliderComponentRGB_A.setColorPanel(colorPanel);

        multiSliderComponentRG_B_A.setColorPanel(colorPanel);

        multiSliderComponentR_GB_A.setColorPanel(colorPanel);

        multiSliderComponentRB_G_A.setColorPanel(colorPanel);

        multiSliderComponentR_GBA.setColorPanel(colorPanel);

        multiSliderComponentRGA_B.setColorPanel(colorPanel);

        multiSliderComponentRBA_G.setColorPanel(colorPanel);

        multiSliderComponentRG_BA.setColorPanel(colorPanel);

        multiSliderComponentRB_GA.setColorPanel(colorPanel);

        multiSliderComponentRA_GB.setColorPanel(colorPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        getContentPane().setLayout(layout);
		this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRG_B_A, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentR_GBA, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRG_BA, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(multiSliderComponentR_G_B_A, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentR_GB_A, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRGA_B, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRB_GA, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(multiSliderComponentRGBA, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRGB_A, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRB_G_A, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRBA_G, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRA_GB, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(multiSliderComponentRGBA, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiSliderComponentRGB_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(colorPanel, 0, 239, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentR_G_B_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(multiSliderComponentRG_B_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentR_GB_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRB_G_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiSliderComponentR_GBA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRGA_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRBA_G, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(multiSliderComponentRG_BA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRB_GA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiSliderComponentRA_GB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        String nativeLF = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(nativeLF);

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                final JFrame frame = new JFrame();
                final SeletorCores3 seletorCores3 = new seletorcores.SeletorCores3();
                frame.add(seletorCores3);
                frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                frame.setTitle("Seletor de Cores");
                frame.setLocationByPlatform(true);
                frame.setName("frmCor"); // NOI18N
                frame.setSize(1041, 800);
                frame.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowOpened(java.awt.event.WindowEvent evt) {
                        seletorCores3.colorPanel.init();
                        KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
                    }
                });


                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private seletorcores.ColorPanel colorPanel;
    private seletorcores.multisliders.MultiSliderComponentRA_GB multiSliderComponentRA_GB;
    private seletorcores.multisliders.MultiSliderComponentRBA_G multiSliderComponentRBA_G;
    private seletorcores.multisliders.MultiSliderComponentRB_GA multiSliderComponentRB_GA;
    private seletorcores.multisliders.MultiSliderComponentRB_G_A multiSliderComponentRB_G_A;
    private seletorcores.multisliders.MultiSliderComponentRGA_B multiSliderComponentRGA_B;
    private seletorcores.multisliders.MultiSliderComponentRGBA multiSliderComponentRGBA;
    private seletorcores.multisliders.MultiSliderComponentRGB_A multiSliderComponentRGB_A;
    private seletorcores.multisliders.MultiSliderComponentRG_BA multiSliderComponentRG_BA;
    private seletorcores.multisliders.MultiSliderComponentRG_B_A multiSliderComponentRG_B_A;
    private seletorcores.multisliders.MultiSliderComponentR_GBA multiSliderComponentR_GBA;
    private seletorcores.multisliders.MultiSliderComponentR_GB_A multiSliderComponentR_GB_A;
    private seletorcores.multisliders.MultiSliderComponentR_G_B_A multiSliderComponentR_G_B_A;
    // End of variables declaration//GEN-END:variables
}
